<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="style/style.css">
    <title>login page</title>
</head>
<body>
    <div class="container">
    <nav class="navbar navbar-expand-lg bg-light  mb-5">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">TODO APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"><span class="material-symbols-outlined">
home
</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../signupuser/home.phtml"><span class="material-symbols-outlined">
person_add
</span></a>
        </li>
        
</ul>
    <img src="../storage/Checklist.png" alt="" class="d-flex" height="40px" width="40px">
    </div>
</div>
</nav>
<div class="login-container row">
    <div class="col">
        <form class="shadow-lg p-3 mb-5 bg-light rounded" action="./process.php" method="POST">
            <h1 class="text-center">login user</h1>
            <?php if(array_key_exists('msg',$_GET)) :  ?>
                <div class="alert alert-<?= $_GET['class'];?>">
                <?= $_GET['msg']; ?>
                </div>
            <?php endif; ?>
            <div class="mb-3">
                <label for="email" class="form-label">Email address</label>
                <input type="email" class="form-control" id="email" name="email">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" class="btn btn-primary" name="submit">Submit</button>
        </form>
    </div>
    <img src="../storage/login.png" alt="" class="col img-thumbnail logo">
    </div>
    <small class="text-muted text-center">you dont have an account yet ! <a href="../signupuser/home.phtml">sign up now !</a></small>
</div>
</body>
</html>