<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="../style/style.css">
    <title>sign up user</title>
</head>
<body>
<div class="container">
<nav class="navbar navbar-expand-lg bg-light  mb-5">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">TODO APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="../loginUser/loginPage.phtml"><span class="material-symbols-outlined">
home
</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../loginUser/loginPage.phtml"><span class="material-symbols-outlined">
login
</span></a>
        </li>
</ul>     
<img src="../storage/Checklist.png" alt="" class="d-flex" height="40px" width="40px">
        </div>
</div>
</nav>
    <h1 class="text-center">sign up user</h1>
    <?php if(array_key_exists('msg',$_GET)): ?>
            <div class="alert alert-<?=$_GET['type']?>">
                <?= $_GET['msg']; ?>
            </div>
    <?php endif; ?>
    <div class="row">
    <div class="sign-up-user-form">
<form class="shadow-lg p-5 rounded col"  method="POST" action="./process.php" enctype="multipart/form-data">
<div class="mb-3">
    <label for="username" class="form-label">username <i class="bi bi-person-circle"></i></label>
    <input type="text" class="form-control" id="username" name="username">
</div>
<div class="mb-3">
    <label for="email" class="form-label">Email address <i class="bi bi-envelope"></i></label>
    <input type="email" class="form-control" id="email" name="email">
</div>
<div class="mb-3">
    <label for="password" class="form-label">Password <i class="bi bi-lock-fill"></i></label>
    <input type="password" class="form-control" id="password" name="password">
</div>
<div class="mb-3">
    <label for="password2" class="form-label"> confirm Password <i class="bi bi-lock-fill"></i></label>
    <input type="password" class="form-control" id="password2" name="password2">
</div>
<div class="mb-3">
    <label for="avatar" class="form-label">choose a profile picture : <i class="bi bi-camera-fill"></i></label>
    <input type="file" class="form-control" id="avatar" name="avatar">
</div>
    <button type="submit" class="btn btn-primary" name="submit">sign up</button>
</form>
    </div>
<div class="col">
<img src="../storage/sign_up.png" class="logo">
</div>
</div>
</div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>